### ISSUE TITLE
The datasets download link does not work

### ISSUE THREAD

**Issue by jikuizhao** [rgopikrishna-vt/Detecting_Irregular_Network_Activity_with_Adversarial_Learning_and_Expert_Feedback#3]
Hi Mr. Gopikrishna,

The dataset download link for CAAD does not work, could you please double-check? Thank you very much.

**Comment by ReihanehGhasemianRoshan** [comment]
Hi, I use the link in below, and it works!
https://drive.google.com/drive/folders/1YXxv-OwIms0olIOxDI0530U8_Tu1FHT5

**Comment by rgopikrishna-vt** [comment]
Thank you for notifying me. I have updated the same.
